Repository ArthurDiogenes/drip-store, pull requests merged in 2025-05, with the labels that each got.

#1 initial commit
  .gitignore
  README.md
  eslint.config.js
  index.html
  package-lock.json
  package.json
  public/vite.svg
  src/App.css
  src/App.jsx
  src/assets/react.svg
  src/index.css
  src/main.jsx
  vite.config.js
Labels: sprint-1

#5 Feature/product card
  package-lock.json
  package.json
  postcss.config.js
  src/App.jsx
  src/assets/img-camisa-star-wars-destaque.png
  src/assets/img-headset-destaque.png
  src/assets/img-produtoEmAlta.png
  src/assets/img-tenis-destaque.png
  src/assets/img-tenis-login-1.png
  src/assets/img-tenis-login-2.png
  src/assets/img-tenis-oferta-especial.png
  src/assets/img-white-sneakers-product -1.png
  src/assets/img-white-sneakers-product -2.png
  src/components/Product-card/ProdutosEmAlta.jsx
  src/components/SpecialOffer/SpecialOffer.jsx
  src/index.css
  tailwind.config.js
Labels: sprint-1

#6 add footer
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.module.css
Labels: sprint-1

#7 updating directory and adding ui/components
  src/App.jsx
  src/components/Navbar/Navbar.module.css
  src/components/ProductCard/ProductCard.jsx
  src/components/layout/Footer.jsx
  src/components/layout/Header.jsx
  src/components/layout/Layout.jsx
  src/components/ui/ActionButton.jsx
  src/components/ui/Checkbox.jsx
  src/components/ui/RadioGroup.jsx
  src/components/ui/button-variants.js
  src/components/ui/button.jsx
  src/components/ui/dialog.jsx
  src/components/ui/dropdown-menu.jsx
  src/components/ui/index.js
  src/components/ui/input.jsx
  src/components/ui/label.jsx
Labels: sprint-1

#8 creating components
  package-lock.json
  package.json
  src/components/Breadcrumb/Breadcrumb.jsx
  src/components/ColorSelector/ColorSelector.jsx
  src/components/ProductGallery/ProductGallery.jsx
  src/components/ProductGallery/ProductGallery.module.css
  src/components/ProductPrice/ProductPrice.jsx
  src/components/ProductRating/ProductRating.jsx
  src/components/SizeSelector/SizeSelector.jsx
Labels: sprint-1

#13 Implementação do componente Header com navegação responsiva
  package-lock.json
  package.json
  src/App.jsx
  src/components/layout/Header.jsx
Labels: sprint-1

#14 product details / app routes
  src/App.jsx
  src/components/Breadcrumb/Breadcrumb.jsx
  src/components/layout/Layout.jsx
  src/pages/Home/Home.jsx
  src/pages/ProductDetail/ProductDetail.jsx
  src/pages/ProductDetail/ProductDetail.module.css
  src/routes/AppRoutes.jsx
Labels: sprint-1

#15 Update README.md
  README.md
Labels: sprint-1

#17 Hotfix
  index.html
  public/images/products/produc-image-7.png
  src/components/ProductCard/ProductCard.jsx
  src/components/ProductGallery/ProductGallery.module.css
  src/components/SpecialOffer/SpecialOffer.jsx
  src/pages/ProductDetail/ProductDetail.jsx
Labels: sprint-1

#22 feature: creating all missing components for the cart page
  src/components/CartItem/CartItem.jsx
  src/components/CartItem/CartItem.module.css
  src/components/CartSummary/CartSUmmary.module.css
  src/components/CartSummary/CartSummary.jsx
  src/components/DiscountCode/DiscountCode.jsx
  src/components/DiscountCode/DiscountCode.module.css
  src/components/ShippingCalculator/ShippingCalculator.jsx
  src/components/ShippingCalculator/ShippingCalculator.module.css
Labels: sprint-2

#23 feature: Cart Page
  src/pages/Cart/Cart.jsx
  src/pages/Cart/Cart.module.css
  src/routes/AppRoutes.jsx
Labels: sprint-2

#24 chore: update Cart page styles and global css
  src/App.css
  src/components/CartItem/CartItem.jsx
  src/components/CartItem/CartItem.module.css
  src/components/CartSummary/CartSUmmary.module.css
  src/components/CartSummary/CartSummary.jsx
  src/components/DiscountCode/DiscountCode.jsx
  src/components/DiscountCode/DiscountCode.module.css
  src/components/ShippingCalculator/ShippingCalculator.jsx
  src/components/ShippingCalculator/ShippingCalculator.module.css
  src/index.css
  src/pages/Cart/Cart.jsx
  src/pages/Cart/Cart.module.css
Labels: sprint-2

#27 carrinho
  src/components/CartItem/CartItem.module.css
  src/pages/Cart/Cart.jsx
Labels: sprint-2

#31 chore: updating routes
  src/routes/AppRoutes.jsx
Labels: sprint-2

#35 Feature/consumo de api
  .gitignore
  package-lock.json
  package.json
  src/components/auth/ProtectedRoute.jsx
  src/contexts/AuthContext.jsx
  src/hooks/useAuth.js
  src/services/authService.js
  src/services/cartService.js
  src/services/categoryService.js
  src/services/productService.js
  src/services/supabase.js
Labels: sprint-2

#36 feature: login page initial release
  public/images/login-shoes.png
  src/assets/icons/facebook.png
  src/assets/icons/gmail.png
  src/components/layout/AuthLayout.jsx
  src/pages/Auth/Login.jsx
  src/pages/Auth/Login.module.css
  src/routes/AppRoutes.jsx
Labels: sprint-2

#37 chore: update bg color, add gradient
  src/components/layout/AuthLayout.jsx
  src/components/layout/AuthLayout.module.css
Labels: sprint-2

#39 feat: implementação da página de compra realizada com sucesso e suas rotas
  src/pages/OrderSuccess/OrderSuccess.jsx
  src/pages/OrderSuccess/OrderSuccess.module.css
  src/routes/AppRoutes.jsx
Labels: sprint-2

#41 feat: add register and register form pages
  src/components/ProductCard/ProductCard.jsx
  src/components/ProductCard/ProductCard.module.css
  src/components/layout/Header.jsx
  src/pages/Auth/Register.jsx
  src/pages/Auth/Register.module.css
  src/pages/Auth/RegisterForm.jsx
  src/pages/Auth/RegisterForm.module.css
  src/pages/ProductList/ProductList.jsx
  src/pages/ProductList/ProductList.module.css
  src/routes/AppRoutes.jsx
Labels: sprint-3

#42 Feat/orders page
  src/components/AccountSidebar/AccountSidebar.jsx
  src/components/AccountSidebar/AccountSidebar.module.css
  src/components/OrderItem/OrderItem.jsx
  src/components/OrderItem/OrderItem.module.css
  src/components/OrdersList/OrdersList.jsx
  src/components/OrdersList/OrdersList.module.css
  src/components/StatusBadge/StatusBadge.jsx
  src/components/StatusBadge/StatusBadge.module.css
  src/pages/Orders/Orders.jsx
  src/pages/Orders/Orders.module.css
  src/routes/AppRoutes.jsx
Labels: sprint-3

#43 feat: add user info page
  src/components/UserInfoItem/UserInfoItem.jsx
  src/components/UserInfoItem/UserInfoItem.module.css
  src/components/UserInfoSection/UserInfoSection.jsx
  src/components/UserInfoSection/UserInfoSection.module.css
  src/pages/UserInfo/UserInfo.jsx
  src/pages/UserInfo/UserInfo.module.css
  src/routes/AppRoutes.jsx
Labels: sprint-3

#45 Feat/creating services to begin integration
  src/App.jsx
  src/contexts/AuthContext.jsx
  src/contexts/UserContext.jsx
  src/services/authService.js
  src/services/cartService.js
  src/services/productService.js
  src/services/userService.js
Labels: sprint-3

#46 Feature/navbar : Melhorar a legibilidade, a estrutura do componente Header, e correção do clique no botão carrinho
  src/components/layout/Header.jsx
Labels: sprint-3

#47 Feat/integration
  src/components/auth/ProtectedRoute.jsx
  src/contexts/UserContext.jsx
  src/hooks/useAuth.js
  src/pages/Auth/Login.jsx
  src/pages/Auth/Register.jsx
  src/pages/Auth/RegisterForm.jsx
  src/routes/AppRoutes.jsx
  src/services/categoryService.js
Labels: sprint-3

#48 Feature/service product list
  src/components/FeaturedProducts/FeaturedProducts.jsx
  src/components/ProductCard/ProductCard.jsx
  src/pages/Home/Home.jsx
  src/pages/ProductList/ProductList.jsx
  src/services/productService.js
Labels: sprint-3

#51 feat: implementa renderização condicional na navbar e corrige bug do carrinho mobile
  src/components/layout/Header.jsx
Labels: sprint-3

#52 Feat/reg
  .gitignore
  src/components/AccountSidebar/AccountSidebar.jsx
  src/components/layout/Header.jsx
  src/pages/Auth/RegisterForm.jsx
  src/services/authService.js
  src/services/supabase.js
Labels: sprint-3

#53 Feat/profile
  src/pages/EditUserInfo/EditUserInfo.jsx
  src/pages/EditUserInfo/EditUserInfo.module.css
  src/pages/UserInfo/UserInfo.jsx
  src/routes/AppRoutes.jsx
  src/services/userService.js
Labels: sprint-3

#55 chore: fix payment methods
  src/pages/AddPaymentMethod/AddPaymentMethod.jsx
  src/pages/AddPaymentMethod/AddPaymentMethod.module.css
  src/pages/PaymentMethods/PaymentMethods.jsx
  src/pages/PaymentMethods/PaymentMethods.module.css
  src/routes/AppRoutes.jsx
Labels: sprint-3

#58 feat: product detail integration
  src/pages/ProductDetail/ProductDetail.jsx
  src/services/productService.js
Labels: sprint-4

#62 Fix/order status display
  src/components/DiscountCode/DiscountCode.jsx
  src/components/OrderItem/OrderItem.jsx
  src/components/OrdersList/OrdersList.jsx
  src/components/ShippingCalculator/ShippingCalculator.jsx
  src/lib/utils.js
  src/pages/Cart/Cart.jsx
  src/pages/Checkout/Checkout.jsx
  src/pages/OrderSuccess/OrderSuccess.jsx
  src/pages/Orders/Orders.jsx
  src/services/couponService.js
  src/services/orderService.js
  src/services/shippingService.js
Labels: sprint-4

#63 feat: add toast, remove alerts
  src/components/DiscountCode/DiscountCode.jsx
  src/components/ShippingCalculator/ShippingCalculator.jsx
  src/components/Toast/Toast.jsx
  src/components/Toast/Toast.module.css
  src/pages/Cart/Cart.jsx
  src/pages/ProductDetail/ProductDetail.jsx
  src/services/shippingService.js
Labels: sprint-4

#70 refactor: padronizar button do banner
  src/components/HeroBanner/HeroBanner.css
Labels: sprint-4

#73 feat: integrate payment methods to checkout page
  src/components/SpecialOffer/SpecialOffer.jsx
  src/components/layout/Footer.jsx
  src/pages/Checkout/Checkout.jsx
Labels: sprint-4

#74 chore: fix 404 style
  src/routes/AppRoutes.jsx
Labels: sprint-4
